version: '3'

services:

  mysql-kc:
    image: mysql/mysql-server:8.0.32
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: lethanh
      MYSQL_PASSWORD: lethanh
      MYSQL_DATABASE: keycloak-service
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    ports:
      - 8181:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: mysql-kc
      DB_PORT: 3306
      DB_USER: lethanh
      DB_PASSWORD: lethanh
      DB_DATABASE: keycloak-service
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network
  auth-service:
    container_name: auth-service
    image: registry.gitlab.com/thanhnguyenle/auth-service:1.1
    ports:
      - 8081:8081
    depends_on:
      - keycloak-w
      - api-gateway
    networks:
      - keycloak-and-mysql-network
  user-service:
    container_name: user-service
    image: registry.gitlab.com/thanhnguyenle/user-service:1.2
    ports:
      - 8082:8082
    depends_on:
      - keycloak-w
      - api-gateway
    networks:
      - keycloak-and-mysql-network
  eureka-server:
    container_name: eureka-server
    image: registry.gitlab.com/thanhnguyenle/eureka-server:1.3
    ports:
      - 8761:8761
    depends_on:
      - keycloak-w
    networks:
      - keycloak-and-mysql-network
  api-gateway:
    container_name: api-gateway
    image: registry.gitlab.com/thanhnguyenle/api-gateway:4.0
    ports:
      - 8080:8080
    depends_on:
      - keycloak-w
      - eureka-server
    networks:
      - keycloak-and-mysql-network
  product-service:
    container_name: product-service
    image: registry.gitlab.com/thanhnguyenle/product-service:2.0
    ports:
      - 8083:8083
    depends_on:
      - keycloak-w
      - eureka-server
    networks:
      - keycloak-and-mysql-network
  order-service:
    container_name: order-service
    image: registry.gitlab.com/thanhnguyenle/order-service:1.0
    ports:
      - 8084:8084
    depends_on:
      - keycloak-w
      - eureka-server
    networks:
      - keycloak-and-mysql-network
  zipkin:
    image: openzipkin/zipkin:2.24
    container_name: zipkin
    environment:
      - JAVA_OPTS=-Xms2g -Xmx2g -XX:+ExitOnOutOfMemoryError
    ports:
      - 9411:9411
    networks:
      - keycloak-and-mysql-network
networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:
